-- DROP TABLE IF EXISTS customers_employers;
-- DROP TABLE IF EXISTS employers;
-- DROP TABLE IF EXISTS accounts;
-- DROP TABLE IF EXISTS customers;
--
--
--
-- create table customers
-- (
--     id         serial not null
--         constraint customers_pkey1
--             primary key,
--     name       varchar,
--     email      varchar,
--     age        integer
-- );
-- create table accounts
-- (
--     id          serial not null
--         constraint accounts_pkey
--             primary key,
--     number   UUID  DEFAULT public.uuid_generate_v4() NOT NULL,
--     currency    varchar,
--     balance     double precision,
--     customer_id integer
--         constraint "customerId"
--             references customers
-- );
-- create table employers
-- (
--     id      integer default nextval('employer_id_seq'::regclass) not null
--         constraint employer_pk
--             primary key,
--     name    varchar,
--     address varchar
-- );