server:
  port: 9000
spring:
  h2:
    console:
      enabled: true
      settings:
        trace: false
logging:
  level:
    org:
    com:
#    springframework:
#        security: DEBUG
---
spring:
  profiles:
    active: dev
---
spring:
  sql:
    init:
      mode: always
      data-locations: classpath:data-h2.sql
#      schema-locations: classpath:schema-h2.sql
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        generate_statistics: false
      show-sql: false
  config:
    activate:
      on-profile: dev
---
spring:
  sql:
    init:
      mode: always
      data-locations: classpath:data-postgres.sql
#      schema-locations: classpath:schema-postgres.sql
  datasource:
    url: jdbc:postgresql://ec2-34-231-42-166.compute-1.amazonaws.com:5432/d7572krnpe47te
    username: xyhrthcvrkjkho
    password: a8161dc21584ad9260530b40b6bd0b8c0b30125d88b4201687947aec46df8501
  jpa:
    defer-datasource-initialization: true
    hibernate:
          ddl-auto: create-drop
    properties:
      hibernate:
        generate_statistics: false
    show-sql: false
  config:
    activate:
      on-profile: prod

