server:
  port: 9000
spring:
  h2:
    console:
      enabled: true
      settings:
        trace: false
#logging:
#  level:
##    org: off
##    com: off
---
spring:
  profiles:
    active: dev
---
spring:
  sql:
    init:
      mode: always
      data-locations: classpath:data-h2.sql
      schema-locations: classpath:schema-h2.sql
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    defer-datasource-initialization: true
  config:
    activate:
      on-profile: dev
---
spring:
  sql:
    init:
      mode: always
      data-locations: classpath:data-postgres.sql
      schema-locations: classpath:schema-postgres.sql
  datasource:
    url: jdbc:postgresql://localhost:5432/BankingApp
    username: postgres
    password: pg123456
  jpa:
    defer-datasource-initialization: true
    hibernate:
    #      ddl-auto: update
    properties:
      hibernate:
        generate_statistics: true
    show-sql: false
  config:
    activate:
      on-profile: prod
welcome:
  message: welcome
